### ISSUE TITLE
Syntax error on Ubuntu 18.04

### ISSUE THREAD

**Issue by wlraider70** [ntalekt/Cox_Data_Usage#6]
Sorry if this is really easy, but I don't know much about code.
I'm getting the following error.

```
$ sudo python coxusage.py
  File "coxusage.py", line 13
    json_file = f"{json_file_location}"
                                           ^
SyntaxError: invalid syntax
```

**Comment by ntalekt** [comment]
Yeah sorry, I meant to archive this repo as it won't work with Cox's new authentication. 

Please see: https://github.com/ntalekt/coxusage-docker
